import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'antd/dist/antd.css'
import {Input, Popconfirm, Table, Typography} from "antd";
import {useState} from "react";
import {SearchOutlined} from "@ant-design/icons";


type User = {
    key: string;
    name: string;
    age: number;
    address: string;
}

const data = [
    {
        key: '1',
        name: 'John Brown',
        age: 32,
        address: 'New York No. 1 Lake Park',
    },
    {
        key: '2',
        name: 'Joe Black',
        age: 42,
        address: 'London No. 1 Lake Park',
    },
    {
        key: '3',
        name: 'Jim Green',
        age: 32,
        address: 'Sidney No. 1 Lake Park',
    },
    {
        key: '4',
        name: 'Jim Red',
        age: 32,
        address: 'London No. 2 Lake Park',
    },
];


const Home: NextPage = () => {

    const [dataSource, setDataSource] = useState(data);
    const [value, setValue] = useState('');
    const {Title} = Typography

    const handleSearch = (dataIndex: 'name' | 'age') => {
        const filteredData = data.filter(entry => {
                const col = entry[dataIndex].toString()
                return col.toLowerCase().includes(value.toLowerCase())
            }
        );
        setDataSource(filteredData);
    }


    const FilterByNameInput = (column: string, dataIndex: 'name' | 'age') => (
        <>
            <div style={{display: "flex", alignItems: 'center', justifyContent: "space-between"}}>
                <Title level={5}>{column}:</Title>
                <Popconfirm
                    title={<Input
                        placeholder="Search Name"
                        value={value}
                        onChange={(e) => setValue(e.target.value)}
                        onKeyDown={(e) => e.keyCode === 13 && handleSearch(dataIndex)}
                    />}
                    onConfirm={(e) => handleSearch(dataIndex)}
                    okText="Search"
                    showCancel={false}

                >
                    <SearchOutlined/>
                </Popconfirm>
            </div>
        </>

    );


    const columns = [
        {
            title: FilterByNameInput('Name', 'name'),
            dataIndex: 'name',
            width: 250
        },
        {
            title: 'Age',
            dataIndex: 'age',
            width: 250
        },
        {
            title: 'Address',
            dataIndex: 'address',
            width: 250
        },
    ];

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>


            <Table columns={columns} dataSource={dataSource}/>

        </div>
    )
}

export default Home
